# good for locally testing the android emulator
# after this is up run: adb connect localhost:5555 && adb wait-for-device && ./gradlew app:connectedCheck
version: '2.3'
services:
  android-emulator:
    container_name: android-emulator
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
    devices:
    - "/dev/kvm"
    ports:
      - "5555:5555"