name: App Test

on:
  pull_request:
    paths:
      - .github/workflows/app-test.yml
      - 'app/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*
  push:
    branches:
      - main
    paths:
      - .github/workflows/app-test.yml
      - 'app/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew app:lint
      - name: Anotate lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: app/build/reports/lint-results.xml
      - name: Archive lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/reports/lint-results.xml
