name: App Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lib_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: check deps
        run: ./gradlew lib:generatePomFileForMavenPublication && diff lib/pom.xml lib/build/publications/maven/pom-default.xml
      - name: lint
        run: ./gradlew lib:lint
      - name: lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: lib/build/reports/lint/report.xml
      - name: checkstyle
          run: ./gradlew lib:checkstyle
      - name: junit5 units tests (with jacoco covarege reports)
          run: ./gradlew lib:jacocoTestReport
      - uses: actions/upload-artifact@v2
        with:
          name: lib-reports
          path: lib/build/reports
      - uses: actions/upload-artifact@v2
        with:
          name: lib-jacoco
          path: lib/build/jacoco

  android_checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: check app dependency update
        run: ./gradlew app:generatePomFileForDebugPublication && diff app/pom.xml app/build/publications/debug/pom-default.xml
      - name: lint
        run: ./gradlew app:lint
      - name: app lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: app/build/reports/lint/report.xml
      - name: checkstyle
        run: ./gradlew app:checkstyle
      - name: junit5 unit tests
        run: ./gradlew app:test
      - name: junit5 instrumented tests (with jacoco coverage reports))
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 18
          script: ./gradlew app:jacocoTestReportDebug
      - uses: actions/upload-artifact@v2
        with:
          name: app-reports
          path: app/build/reports
      - uses: actions/upload-artifact@v2
        with:
          name: app-jacoco
          path: app/build/jacoco

  upload-coverage-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
          run: ls -R
      - name: codecov upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/coverage/debug/jacoco.xml,lib/build/reports/jacoco/jacoco.xml
