name: App Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lib_checks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: check deps
        run: ./gradlew lib:generatePomFileForMavenPublication && diff lib/pom.xml lib/build/publications/maven/pom-default.xml
      - name: lint
        run: ./gradlew lib:lint
      - name: lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: lib/build/reports/lint/report.xml
      - name: checkstyle
        run: ./gradlew lib:checkstyle
      - name: junit5 units tests (with jacoco covarege reports)
        run: ./gradlew lib:jacocoTestReport
      - uses: actions/upload-artifact@v2
        with:
          name: lib-reports
          path: lib/build/reports

  android_checks:
    runs-on: self-hosted
    # https://github.com/natario1/CameraView/blob/master/.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        # EMULATOR_API: [22, 23, 24, 25, 26, 27, 28]
        EMULATOR_API: [22]
        include:
#          - EMULATOR_API: 28
#            EMULATOR_ARCH: x86_64
#          - EMULATOR_API: 27
#            EMULATOR_ARCH: x86_64
#          - EMULATOR_API: 26
#            EMULATOR_ARCH: x86_64
#          - EMULATOR_API: 25
#            EMULATOR_ARCH: x86
#          - EMULATOR_API: 24
#            EMULATOR_ARCH: x86
#          - EMULATOR_API: 23
#            EMULATOR_ARCH: x86
          - EMULATOR_API: 22
            EMULATOR_ARCH: x86
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: check app dependency update
        run: ./gradlew app:generatePomFileForDebugPublication && diff app/pom.xml app/build/publications/debug/pom-default.xml
      - name: lint
        run: ./gradlew app:lint
      - name: app lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: app/build/reports/lint/report.xml
      - name: checkstyle
        run: ./gradlew app:checkstyle
      - name: junit5 instrumented tests (with jacoco coverage reports))
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          profile: Nexus 5X
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated -camera-front emulated -gpu swiftshader_indirect
          script: ./gradlew app:connectedCheck && ./gradlew app:jacocoTestDebugUnitTestReport
      - uses: actions/upload-artifact@v2
        with:
          name: app-reports
          path: app/build/reports

  upload-coverage-reports:
    needs: [lib_checks, android_checks]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: codecov upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app-reports/coverage/debug/report.xml,lib-reports/jacoco/jacoco.xml
