name: App Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lib_checks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.0.4'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: lint
        run: ./gradlew lib:lint
      - name: lint results
        uses: yutailang0119/action-android-lint@v3
        with:
          report-path: lib/build/reports/lint/report.xml
      - name: checkstyle
        run: ./gradlew lib:checkstyle
      - name: junit5 units tests (with jacoco covarege reports)
        run: ./gradlew lib:jacocoTestReport
      - uses: actions/upload-artifact@v3
        with:
          name: lib-reports
          path: lib/build/reports

  android_checks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.0.4'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: lint
        run: ./gradlew app:lint
      - name: app lint results
        uses: yutailang0119/action-android-lint@v3
        with:
          report-path: app/build/reports/lint/report.xml
#      - name: checkstyle
#        run: ./gradlew app:checkstyle
#      - name: junit5 instrumented tests (with jacoco coverage reports))
#        run: adb connect android-emulator:5555 && adb wait-for-device && ./gradlew app:connectedCheck && ./gradlew app:jacocoTestDebugUnitTestReport
      - uses: actions/upload-artifact@v3
        with:
          name: app-reports
          path: app/build/reports

  integration-tests:
    needs: [lib_checks, android_checks]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.0.4'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: run proxy-client test
        run: ./gradlew proxy:test --info
      - uses: actions/upload-artifact@v3
        with:
          name: proxy-reports
          path: proxy/build/reports

  upload-coverage-reports:
    needs: [lib_checks, android_checks]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: codecov upload
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app-reports/jacoco/jacoco.xml,lib-reports/jacoco/jacoco.xml
