name: App Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  android_checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: check app dependency update
        run: ./gradlew app:generatePomFileForDebugPublication && diff app/pom.xml app/build/publications/debug/pom-default.xml
      - name: check lib dependency update
        run: ./gradlew lib:generatePomFileForMavenPublication && diff lib/pom.xml lib/build/publications/maven/pom-default.xml
      - name: lint
        run: ./gradlew lib:lint app:lint
      - name: app lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: app/build/reports/lint/report.xml
      - name: lib lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: lib/build/reports/lint/report.xml
      - name: checkstyle
        run: ./gradlew lib:checkstyle app:checkstyle
      - name: junit5 unit tests
        run: ./gradlew lib:test app:test
      - name: junit5 instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 18
          script: ./gradlew app:connectedCheck
      - name: jacoco app debug coverage reports
        uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 18
            script: ./gradlew app:combinedTestReportDebug && ./gradlew app:combinedTestReportDebug
      - name: jacoco lib debug coverage reports
        run: ./gradlew lib:jacocoTestReport
      - name: codecov upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/jacocoCombined/debug/jacoco.xml,lib/build/reports/jacoco/jacoco.xml
      - name: archive reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            app/build/reports
            lib/build/reports
